### ISSUE TITLE
Support creating non construct-classes at top-level

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#189]
In the CDK there are many classes that do not extend `construct.Construct` (e.g. `TextWidget`). When processing the input template, when deCDK encounters a resource of such type, it should create an instance and allow it to be referenced by other resources. Example:

```yaml
Title:
  Type: aws-cdk-lib.aws_cloudwatch.TextWidget # non-construct class
  Properties:
    markdown: "# Key Performance Indicators"
ServiceDashboard:
  Type: aws-cdk-lib.aws_cloudwatch.Dashboard
  Properties:
    widgets:
    - - Ref: Title # construct referencing a non-construct
```

Equivalent CDK code in TypeScript:

```ts
const title = new cloudwatch.TextWidget({
  markdown: '# Key Performance Indicators'
});
const serviceDashboard = new cloudwatch.Dashboard(this, 'ServiceDashboard', {
  widgets: [[title]]
});
```
