### ISSUE TITLE
Support CFN intrinsic functions

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#190]
All CFN [intrinsic functions][1] should be translated to their CDK counterparts. Example:

```yaml
Widget:
  Type: aws-cdk-lib.aws_cloudwatch.LogQueryWidget
  Properties:
    logGroupNames:
      Fn::Split:
      - "|"
      - a|b|c
```

should generate the equivalent CDK code:

```ts
new cloudwatch.LogQueryWidget({
  logGroupNames: Fn.split('|', 'a|b|c')
});
```

[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
