### ISSUE TITLE
Support constructs referencing L1 resources

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#202]
Creating constructs in CDK frequently requires referencing other resources. For example, when creating a Lambda function, you may specify a custom execution role, which is defined by the IRole interface. Or when creating an EC2 security group, you are expected to provide a VPC resource, which is defined by the IVpc interface. The CDK library uses these interfaces (IRole, IVpc) in order to add strongly-typed APIs while allowing underlying classes to change their implementation details as needed. It also allows respresenting “unowned” resources within CDK apps. (See [DESIGN_GUIDELINES](https://github.com/aws/aws-cdk/blob/master/docs/DESIGN_GUIDELINES.md#construct-interface) for more details.)

When customers use deCDK, they will expect to be able to use constructs alongside existing raw CloudFormation resources, including having their constructs reference their existing CloudFormation resources. However, the existing CDK classes representing raw CloudFormation resources do not implement interfaces of the corresponding resources (IRole, IVpc). That is, you cannot pass a CfnRole where an IRole is expected in the code. Thus in order for CDK constructs to reference raw CloudFormation resources, we would need to raise L1s to the L2 level.

**Comment by mrgrain** [comment]
I wonder if something like this would work out of the box:
```yaml
Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
  Lambda:
    Type: aws-cdl-lib.aws_lambda.Function
    Properties:
       Code:
         aws-cdk-lib.aws_lambda.Code.fromBucket:
           bucket: { Ref: "SourceBucket"},
           key: "foo-bar"
  }
```

**Comment by rix0rrr** [comment]
I think there's nothing to be done other than a set of heuristics like this, yes.

**Comment by rix0rrr** [comment]
OR: we choose not to do this at all, and have users use the method call syntax to do the upleveling by hand. 

Honestly, this seems like a feature with a lot of possible rough edge cases, and we haven't proved out the need for them yet. So, skip for MVP?

**Comment by rix0rrr** [comment]
Honestly -- list of heuristics has the problem that by changing the construct library we might fall into a different branch, which might change backwards compatibility.

**Comment by rix0rrr** [comment]
So I think it cannot work.

**Comment by mrgrain** [comment]
My thoughts: 

- I don't like the ambiguity of it. It's a lot of guesswork which lifting method will be used. And if I remember correctly, some Constructs offer different features when fromAttributes or fromArn is used. That makes it even harder for users to know what will be happening.

- What implications has it that in deCDK "uplifting" will mostly be related to _future_ resources, contrary to CDK where `fromXyz` is mostly used to reference _existing_ resources.

- These APIs are a mess in CDK already. Should we clean it up there? (E.g. have `fromCfn` methods for everything or something else consistent)

- `fromAttributes` feels safe, if the underlying resource has attributes
- So does `fromArn` if the Resource exports an ARN

- All the inconsistencies appear to originate from the fact that Ref can be different things for different Resources. For buckets, it's the Bucket Name, so we added `fromBucketName`. For VpcLink, Ref is the VpcLink ID, so we added `from fromVpcLinkId`. Even for LogStream: Ref is the LogStream name, so `fromLogStreamName ` should work.

- This currently works, should be rather try and improve the syntax here? (`CDK::Args` is needed because we cannot infer an ID. However since it's inline we could generate an ID for the user, they won't be able to use the Construct then, but that's okay. If they would want re-use, they could define it at the top-level)
```
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
  SiteDeployment:
    Type: aws-cdk-lib.aws_s3_deployment.BucketDeployment
    Properties:
      sources: []
      destinationBucket:
        aws-cdk-lib.aws_s3.Bucket.fromBucketName:
          CDK::Args:
            - Ref: CDK::Scope
            - 'SiteBucketL2'
            - Ref: SiteBucket
```
