### ISSUE TITLE
Only use Fully Qualified Names

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#241]
## Tracking related issues:
- [ ] #50 

---
We must use FQNs for all complex property arguments:
```
Resources:
    MyLambda:
        Type: aws-cdk-lib.aws_lambda.Function
        Properties:
            code:  # Code
                fromAsset: '/tmp' 
                aws-cdk-lib.aws_lambda.Code.fromAsset: '/tmp'  # <-- THIS
                  
            timeout:
                seconds: 5  
                Duration.seconds: 5   
                aws-cdk-lib.Duration.seconds: 5    # <-- THIS
```
Shorter forms may change meaning if the underlying CDK library is changed in valid ways.

Examples:
```
        Properties:
            code:  # Code
                fromAsset: '/tmp'
```
The syntax above can only work because the `code` property is typed as a `Code` class which has static factory functions. If the type is changed to either abstract class `BaseCode` or interface `ICode`, we would lose the ability to know that the factory functions exist on the Code class. (Changing property types to supertypes — a.k.a. weakening preconditions — is a valid type evolution in jsii).
```
            timeout:
                Duration.seconds: 5  
```
The syntax above requires that `Duration` resolves to `aws-cdk-lib.Duration`. If `aws-cdk-lib.aws_lambda.Duration` ever comes into existence, it would take precedence, changing the meaning of `Duration.seconds`. 

--- 

**POTENTIALLY We could add syntactic sugars, import rules or resolutions rules. These are noted here, but out of scope until a decision is made:**
- In a construct of type `aws-cdk-lib.aws_lambda.Function` we could assume that any name that is not a FQN is located in the same namespace. E.g. `Code.fromAsset` becomes `aws-cdk-lib.aws_lambda.Code.fromAsset`. However `Duration.seconds` would always have to be written as `aws-cdk-lib.aws_lambda.Duration.seconds`
```
        Properties:
            code:  # Code
                Code.fromAsset: '/tmp'  # <-- this might be special cased
            timeout:
                aws-cdk-lib.Duration.seconds: 5   # <-- but this requires an FQN
```

- Constructs could have an optional field `Namespace` on the top-level (next to `Type`). If set, any name that is not a FQN is located in the set namespace. This would also apply to the value in `Type`
```
Resources:
    MyLambda:
        Namespace: aws-cdk-lib.aws_lambda
        Type: Function
        Properties:
            code:  # Code
                Code.fromAsset: '/tmp'  # <-- THIS, Namespace used
            timeout:
                aws-cdk-lib.Duration.seconds: 5    # <-- requires FQN
```

- Have the user opt-in to risky namespace resolution. The original syntax without FQN would work, however the user assumes the risk that it might break without notice:
```
NamespaceResolution: AUTO_RISKY  # <-- user has to opt-in to risky behaviour
Resources:
    MyLambda:
        Type: aws-cdk-lib.aws_lambda.Function
        Properties:
            code:  # Code
                fromAsset: '/tmp' # <-- works, but might break in future
            timeout:
                seconds: 5  #  <-- works, but might break in future
```

- Import maps
```
Imports:
  cdk: aws-cdk-lib
  lambda: aws-cdk-lib.aws_lambda
  Duration: aws-cdk-lib.Duration
Resources:
    MyLambda:
        Type: aws-cdk-lib.aws_lambda.Function
        Properties:
            code:  # Code
                lambda.Code.fromAsset: '/tmp' # <-- can map a sub-module namespace
            timeout:
               cdk.Duration.seconds: 5  #  <-- or the root namespace
               Duration.seconds: 5  #  <-- or a class
```
