### ISSUE TITLE
Bug: error specifying IAM policy

### ISSUE THREAD

**Issue by misterjoshua** [cdklabs/decdk#243]
I'm trying to grant a lambda function access to an S3 bucket so the lambda function can cache its result. I tried to hand-code an IAM Policy Document by adding it to the function's initial policy, but unfortunately, I'm getting an error about a missing parameter for `aws-cdk-lib.aws_iam.PolicyStatement.fromJson()`.

**decdk version:** 2.0.0-pre.194
**aws-cdk version:** 2.40.0 (build 56ba2ab)

```yaml
# yaml-language-server: $schema=./decdk.schema.json
# ^ Use the redhat.vscode-yaml extension for vscode to get completion
Resources:

  SvgRasterFunction:
    Type: aws-cdk-lib.aws_lambda.Function
    Properties:
      runtime: PROVIDED_AL2
      handler: NOT_APPLICABLE
      memorySize: 10240
      code: 
        fromAsset:
          path: target/x86_64-unknown-linux-musl/release
          exclude:
            - "*"
            - "!bootstrap"
      environment:
        CACHE_BUCKET: { Fn::GetAtt: CacheBucket.bucketName }
      initialPolicy:
      - fromJson:
          Version: 2012-10-17
          Statement:
          - Sid: FirstStatement
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            Resource:
            - { Fn::GetAtt: CacheBucket.arn }
            - { Fn::Join: ["", [{ Fn::GetAtt: CacheBucket.arn }, "/*"]]}
  
  CacheBucket:
    Type: aws-cdk-lib.aws_s3.Bucket
```

```shell
josh@nyx:~/proj/shards-next/svg-raster$ cdk --app "decdk decdk.yaml" deploy
TypeError: Expected required parameter 'obj' for aws-cdk-lib.aws_iam.PolicyStatement.fromJson

Subprocess exited with error 1
```

**Comment by misterjoshua** [comment]
Ah. I figured it out.

**Comment by mrgrain** [comment]
@misterjoshua Thanks for coming up with this example. DeCDK should definitely support nested intrinsics. Re-opening so I can keep track of it

**Comment by mrgrain** [comment]
Notes to myself:
- the need for `obj` will go away with #265 
- I've got the example working with `Fn:GetAtt`, however not with `Ref`
- `Ref` is used in an unknown type context here and thus should resolve to the CDK intrinsic, not the Construct object

**Comment by mrgrain** [comment]
Simplified template for the Ref issue:
```
{
      Resources: {
        Bucket: {
          Type: 'AWS::S3::Bucket',
          Properties: {
            BucketName: 'my-bucket',
          },
        },
        Topic: {
          Type: 'aws-cdk-lib.aws_sns.Topic',
          Properties: {
            displayName: { 'Ref': Bucket },
          },
        },
      },
    }
```

**Comment by mrgrain** [comment]
@misterjoshua The latest release makes this possible
```yaml
      - fromJson:
          obj:
            Resource:
            - { Ref: CacheBucket }
            - { Fn::Join: ["", [{ Ref: CacheBucket }, "/*"]] }
```
