### ISSUE TITLE
Use `Fn::GetProp` to get values from CDK constructs

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#245]
`{ Fn::GetProp }` is the deCDK counterpart to `{ Fn::GetAtt }`. The result is always a deCDK value.

 `{CDK::GetProp: [x, 'Prop']}` | Used in CFN context | Used in deCDK context
-- | -- | --
x = CfnResource | (error) | (error)
x = CdkConstruct | assertCfnValue(x[att]) | x[att]

`{ Fn::GetAtt }` will always retrieve CloudFormation attributes (for reasons below). Therefore, the result is always a CFN value.

 `{Fn::GetAtt: [x, 'CfnAtt']}`  | Used in CFN context | Used in deCDK context
-- | -- | --
x = CfnResource  | x[att] | x[att]
x = CdkConstruct | findDefaultCfnResource(x).getAtt(att)  | findDefaultCfnResource(x).getAtt(att) 

---
## Why `{ Fn::GetAtt }` only references CloudFormation attributes

In the current deCDK, `{ Fn::GetAtt }` allows referencing properties on L2s. For example:
```
Resources:
  CfnResource: # Some CFN resource
  DecdkResource: # Some deCDK resource
  
  OtherResource: 
    Properties:
      Something: { 'Fn::GetAtt': ['DecdkResource', 'decdkProp'] } // -> decdkResource.decdkProp
```
If we continue to allow this, there will be an inconsistency with `{ Ref }:`

* `{ Ref }` will have its semantics consistent with CFN `{ Ref }` , regardless of whether you are referencing a CFN value or a deCDK value.
* `{ Fn::GetAtt } `behaves differently depending on whether you reference a CFN value or a deCDK value:
```
Resources:
  CfnResource: # Some CFN resource
  DecdkResource: # Some deCDK resource
  
  OtherResource:
    Properties:
      Something1: { 'Ref': CfnResource }    # Works
      Something2: { 'Ref': DecdkResource }  # Works
      Something3: { 'Fn::GetAtt': ['CfnResource', 'CfnAttr'] }   # Works
      Something4: { 'Fn::GetAtt': ['DecdkResource', 'CfnAttr'] } # DOES NOT WORK
```
This behavior is confusing, and you might even need a second to figure out why: `CfnAttr` does not exist on the CDK construct (it's a CFN attribute). Even worse when the CFN attr and CDK prop are named the same: `Name` vs `name`. The difference becomes only the case of the first letter. Which is why we make a distinction between `{ Fn::GetAtt }` and `{ Fn::GetProp }`.
