### ISSUE TITLE
Positional Arguments

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#264]
Enum-like static methods should take arguments like this
```yaml
MyLambda:
  Type: aws-cdk-lib.aws_lambda.Code
  Properties:
    timeout:
      "aws-cdk-lib.Duration.seconds": 5
```
as opposed to
```yaml
      "aws-cdk-lib.Duration.seconds": 
        amount: 5 
```

---

Example for method with two args:
```json
"MyLambda": {
  "Type": "aws-cdk-lib.aws_lambda.Code",
  "Call": {
    "aws-cdk-lib.aws_lambda.Code.fromBucket": [{ "Ref": "SourceBucket"}, "foo-bar"]
  }
}
```
