### ISSUE TITLE
Cannot use aws-cdk-lib.aws_ec2.InstanceType

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#305]
Given the following template

```yaml
Resources:
  VPC:
    Type: aws-cdk-lib.aws_ec2.Vpc
  ASG:
    Type: aws-cdk-lib.aws_autoscaling.AutoScalingGroup
    Properties:
      vpc:
        Ref: VPC
      instanceType:
        aws-cdk-lib.aws_ec2.InstanceType: t2.micro
      machineImage:
        aws-cdk-lib.aws_ec2.AmazonLinuxImage: {}
```

Results in:
- Invalid JSON Schema error
- `Error: Type 'aws-cdk-lib.aws_ec2' not found in assembly aws-cdk-lib`
