### ISSUE TITLE
Rename the `On` property

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#345]
In YAML, `On` is a keyword, equivalent to `true`. While we could keep this name, it forces a bad experience on customers, who have to quote this property:

```yaml
Alias:
  'On': MyFunction
  Call:
    addAlias: live
```

Possible names, in no particular order:

* `Target`
* `Receiver`
* `OnInstance`
* `OnObject`
* `OnConstruct`
