### ISSUE TITLE
Allow in-line calls to factory methods

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#349]
Some static factory methods produce constructs. They can be called in-line, but `CDK::Args` (with explicit scope and id) must be used, as in the following example:

```yaml
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
  SiteDeployment:
    Type: aws-cdk-lib.aws_s3_deployment.BucketDeployment
    Properties:
      sources: []
      destinationBucket:
        aws-cdk-lib.aws_s3.Bucket.fromBucketName:
          CDK::Args:
            - Ref: CDK::Scope
            - 'SiteBucketL2'
            - Ref: SiteBucket
```

Add support for the same inference mechanism that is available at the top level, allowing users to write this, instead:

```yaml
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
  SiteDeployment:
    Type: aws-cdk-lib.aws_s3_deployment.BucketDeployment
    Properties:
      sources: []
      destinationBucket:
        aws-cdk-lib.aws_s3.Bucket.fromBucketName:
          Ref: SiteBucket
```
