### ISSUE TITLE
Support alpha modules

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#351]
Only the stable modules, from `aws-cdk-lib` are supported at the moment. This should work, for example:

```yaml
Resources:
  VPC:
    Type: aws-cdk-lib.aws_ec2.Vpc
  AwsManagedEnvironment:
    Type: '@aws-cdk/aws-batch-alpha.ComputeEnvironment'
    Properties:
      computeResources:
        vpc:
          Ref: VPC
```
