### ISSUE TITLE
Support (and/or explicitly test) array access on Construct properties

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#355]
Given a template like this:
```yaml
Resources:
  MyVpc:
    Type: aws-cdk-lib.aws_ec2.Vpc
Outputs:
  SubnetOneAz:
    Value:
      CDK::GetProp: MyVpc.publicSubnets.0.availabilityZone
```

We can use `CDK::GetProp` to access properties in arrays.

Note: This might already work, but is not explicitly tested.
