### ISSUE TITLE
Nested property instance call

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#371]
When calling an instance method on a nested property like this:
```ts
declare otherResource: SomeConstruct;
otherResource.nested.addThing("value");
```

The nested access should be via `On`, representing that `On` can be a Ref or `CDK::GetProp` value:
```yaml
MyResource:
  On: OtherResource.nested
  Call:
    addThing: value
```

Currently the nested access is handled in `Call`
```yaml
MyResource:
  On: OtherResource
  Call:
    nested.addThing: value # let's not do this
```
