### ISSUE TITLE
Use same casing for properties as CloudFormation

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/decdk#43]
If you're writing a template with both CFN resources and construct resources, there's a disparity in the casing of properties:

```
RootRole:
  Type: 'AWS::IAM::Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
          Action:
            - 'sts:AssumeRole'
MyRole:
  Type: aws-cdk-lib.aws_iam.Role
  Properties:
    assumedBy:
      aws-cdk-lib.aws_iam.ServicePrincipal:
        service: "lambda.amazonaws.com"
    description: "Example role..."
    roleName: MyRoleName
```

I think construct properties in decdk templates should probably have the same casing, e.g. `AssumedBy`, `Description`, `RoleName` etc.

It's also possible we could allow either casing.
