### ISSUE TITLE
Resource type names should match CloudFormation nomenclature

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/decdk#44]
If you look at a template with both CloudFormation resources and CDK constructs, the types look very different (`AWS::IAM::Role` vs `aws-cdk-lib.aws_iam.Role`):

```
RootRole:
  Type: 'AWS::IAM::Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
          Action:
            - 'sts:AssumeRole'
MyRole:
  Type: aws-cdk-lib.aws_iam.Role
  Properties:
    assumedBy:
      aws-cdk-lib.aws_iam.ServicePrincipal:
        service: "lambda.amazonaws.com"
    description: "Example role..."
    roleName: MyRoleName
```

Construct type names should be named in matching style their original CloudFormation type names, such as `CDK::IAM::Role` or `AWSCDK::IAM::Role`.
