### ISSUE TITLE
Unable to reference construct in cloudformation resource

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/decdk#52]
Example:

```
'$schema': './cdk.schema.json'
Resources:
  MyBucket:
    Type: aws-cdk-lib.aws_s3.Bucket
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs16.x
      Role: arn:aws:iam::123456789012:role/lambda-role
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = function(event) {
              console.log("hello world!")
          }
      Description:
        Ref: MyBucket
```

throws the error

```
Error: Element used in Ref expression with logical ID: 'MyBucket' not found
```

This also occurs when using `Fn::GetAtt` - for example:

```
"$schema": "./cdk.schema.json"
Resources:
  MyFunction:
    Type: aws-cdk-lib.aws_lambda.Function
    Properties:
      handler: index.handler
      runtime: NODEJS_14_X
      code:
        fromInline:
          code: 'exports.handler = function() { console.log("hello world"); }'
  MyVersion:
    Type: AWS::Lambda::Version
    Properties:
      functionName:
        Fn::GetAtt:
          - MyFunction
          - functionName
```

throws the error:

```
Error: Resource used in GetAtt expression with logical ID: 'MyFunction' not found
```

This error appears because after the bucket is generated, it's given a logical ID with a unique hash (e.g. `MyBucket7A3B26`), which is not visible to the intrinsic functions.

In cases where constructs create multiple resources, it should just refer to the resource of the default node (accessed via `myConstruct.node.defaultChild`).
